### ISSUE TITLE
Cant use PCI in a word, why?

### ISSUE THREAD

**Issue by hunar1997** [chochain/nanoFORTH#6]
If i type `10 PCI` in the terminal, it works.
but typing `: XXX 10 PCI ;` throws an error
PCI  ?? OK

**Comment by chochain** [comment]
Hi Hunar,

Thank you for taking interest in nanoFORTH. 
In Forth, some words (functions) are mark 'immediate'. Instead of becoming part of other word, they get executed immediately once seen by the interpreter. 
They behave like OS commands. For example DMP, SAV, LD, SEX, SEE, WRD, BYE are. Also, variable declaration VAL, VAR, FGT, and your interrupt handler setting PCI, TMI.

Actually the intention of PCI is to setup Ping Change Interrupt handler. For example
: x10 ." p10 hit" ;   \ define a word as our handler
10 PCI x10           \ set it for ping 10 change ISR (interrupt service routine)
1 PCE                   \ enable Ping Change Interrupt and start capturing

Let me know if  you have a special need. I might find a way to 'fix' it for you. 

Chochain

**Comment by hunar1997** [comment]
Thank you :D
I'm actually familiar with Forth.

afew other questions:
* The meta programming words are (`CRE` `,` `C,` `'` `EXE`) I was hoping for `immediate` and `does>` do I have access to `immediate`? can i theoretically implement `does>` with the builtin words?
* You say in the docs about meta words `available only via source recompilation with N4_META set to 1` but in the source code Its called `N4_DOES_META` and as far as I can see it is set to 1 already in the source code. but I cant seem to see the meta words in the `Wokwi` website even after setting the flag to 1. is that a problem in `Wokwi`? I added `#define N4_DOES_META 1` before and after the `#inlcude ...`
* When i put code using `n4_setup(code);` does that also take space in the limited RAM space? or it only consumes the Flash Memory
* If i make a word then enter `SAV`, now what happens if I enter `SAV` again? would I have two of the same word in EEPROM?

**Comment by chochain** [comment]
Huner,
I'm excited that someone has actually looked into the source code and trying to improve upon it. That's how a project gets better.
* Built-in word lists are defined in n4_asm.cpp. Since nanoFORTH has no immediate bit as classic Forth. Currently one can only expand immediate word to the list and add handler in _immediate. On the other hand does> works and can be use like this : CST CRE , DO> @ ; and 31416 CST PI to defines a constant. I haven't verify other more elaborate cases.
* N4_DO_META it should be, I'll update the doc. Thank you. I haven't but will check what's up with Wokwi. They might need library refresh.
* Extra word (kept in PROGMEM) or function, unless allocates static variable, takes up only Flash once compiled.
* SAV checks HERE to see whether enough space, and instead of append, it simply overwrites from addr 0 of EEPROM.
Regards - Chochain

**Comment by hunar1997** [comment]
Thank you :D
